import { jsPDF } from 'jspdf';
import 'jspdf-autotable';
import html2canvas from 'html2canvas';
import { saveAs } from 'file-saver';
import QRCode from 'qrcode';

export const exportToPDF = async (data, options = {}) => {
    const doc = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4'
    });

    const {
        title = 'Prescription Analysis Report',
        includeTimestamp = true,
        includeQR = true,
        includeSignature = true
    } = options;

    // Header
    doc.setFontSize(20);
    doc.setTextColor(33, 150, 243);
    doc.text(title, 105, 20, { align: 'center' });

    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text(`Report ID: ${generateReportId()}`, 105, 30, { align: 'center' });

    if (includeTimestamp) {
        doc.text(`Generated: ${new Date().toLocaleDateString()} ${new Date().toLocaleTimeString()}`, 105, 35, { align: 'center' });
    }

    // Patient Information Section
    doc.setFontSize(14);
    doc.setTextColor(0, 0, 0);
    doc.text('Patient Information', 20, 50);
    doc.setDrawColor(200, 200, 200);
    doc.line(20, 52, 190, 52);

    doc.setFontSize(10);
    const patientInfo = [
        ['Name:', data.patientName || 'Not specified'],
        ['Date of Birth:', data.dob || 'Not specified'],
        ['Prescription Date:', data.date || 'Not specified'],
        ['Doctor:', data.doctor || 'Not specified'],
        ['Clinic/Hospital:', data.clinic || 'Not specified']
    ];

    doc.autoTable({
        startY: 55,
        head: [['Field', 'Value']],
        body: patientInfo,
        theme: 'grid',
        headStyles: { fillColor: [33, 150, 243], textColor: 255 },
        styles: { fontSize: 9 },
        margin: { left: 20, right: 20 }
    });

    // Medications Table
    const medicationsY = doc.lastAutoTable.finalY + 15;
    doc.setFontSize(14);
    doc.text('Medications', 20, medicationsY);
    doc.line(20, medicationsY + 2, 190, medicationsY + 2);

    const medData = data.medications.map((med, index) => [
        index + 1,
        med,
        data.dosages?.[index] || '',
        data.instructions?.[index] || '',
        data.frequencies?.[index] || '',
        data.durations?.[index] || ''
    ]);

    doc.autoTable({
        startY: medicationsY + 5,
        head: [['#', 'Medication', 'Dosage', 'Instructions', 'Frequency', 'Duration']],
        body: medData,
        theme: 'grid',
        headStyles: { fillColor: [76, 175, 80], textColor: 255 },
        alternateRowStyles: { fillColor: [245, 245, 245] },
        styles: { fontSize: 8, cellPadding: 2 },
        margin: { left: 20, right: 20 },
        columnStyles: {
            0: { cellWidth: 10 },
            1: { cellWidth: 40 },
            2: { cellWidth: 30 },
            3: { cellWidth: 45 },
            4: { cellWidth: 25 },
            5: { cellWidth: 25 }
        }
    });

    // Warnings Section
    if (data.warnings && data.warnings.length > 0) {
        const warningsY = doc.lastAutoTable.finalY + 15;
        doc.setFontSize(14);
        doc.setTextColor(244, 67, 54);
        doc.text('Important Warnings', 20, warningsY);
        doc.setDrawColor(244, 67, 54);
        doc.line(20, warningsY + 2, 190, warningsY + 2);

        doc.setFontSize(9);
        doc.setTextColor(0, 0, 0);
        data.warnings.forEach((warning, index) => {
            const y = warningsY + 10 + (index * 6);
            doc.text(`• ${warning}`, 25, y);
        });
    }

    // Instructions Section
    if (data.instructions && data.instructions.length > 0) {
        const instructionsY = doc.lastAutoTable.finalY + (data.warnings?.length || 0) * 6 + 25;
        doc.setFontSize(14);
        doc.setTextColor(255, 152, 0);
        doc.text('Additional Instructions', 20, instructionsY);
        doc.setDrawColor(255, 152, 0);
        doc.line(20, instructionsY + 2, 190, warningsY + 2);
    }

    // Footer
    const footerY = 280;
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text('This report is generated by Prescription Interpreter Pro', 105, footerY, { align: 'center' });
    doc.text('For informational purposes only. Consult a healthcare professional.', 105, footerY + 5, { align: 'center' });

    // QR Code
    if (includeQR) {
        const qrData = JSON.stringify({
            reportId: generateReportId(),
            timestamp: new Date().toISOString(),
            medications: data.medications,
            confidence: data.confidenceScore
        });

        const qrUrl = await QRCode.toDataURL(qrData, { width: 40, margin: 1 });
        doc.addImage(qrUrl, 'PNG', 160, footerY - 15, 25, 25);
    }

    // Signature
    if (includeSignature) {
        doc.setFontSize(9);
        doc.text('Digitally Generated', 25, footerY - 10);
        doc.text(`Confidence Score: ${data.confidenceScore || 0}%`, 25, footerY - 5);
    }

    return doc.output('blob');
};

export const exportToJSON = (data, options = {}) => {
    const exportData = {
        ...data,
        metadata: {
            exportDate: new Date().toISOString(),
            version: '1.0',
            format: 'JSON',
            ...options.metadata
        }
    };

    if (options.includeRawText) {
        exportData.rawText = data.extractedText;
    }

    if (options.includeMetadata) {
        exportData.analysisMetadata = {
            confidence: data.confidenceScore,
            processingTime: data.processingTime,
            modelVersion: data.modelVersion
        };
    }

    return JSON.stringify(exportData, null, 2);
};

export const exportToCSV = (data, options = {}) => {
    const headers = ['Medication', 'Dosage', 'Instructions', 'Frequency', 'Duration', 'Warnings'];
    const rows = [];

    // Find max length
    const maxLength = Math.max(
        data.medications?.length || 0,
        data.dosages?.length || 0,
        data.instructions?.length || 0,
        data.frequencies?.length || 0,
        data.durations?.length || 0,
        data.warnings?.length || 0
    );

    for (let i = 0; i < maxLength; i++) {
        rows.push([
            data.medications?.[i] || '',
            data.dosages?.[i] || '',
            data.instructions?.[i] || '',
            data.frequencies?.[i] || '',
            data.durations?.[i] || '',
            data.warnings?.[i] || ''
        ]);
    }

    const csvContent = [
        headers.map(escapeCSV).join(','),
        ...rows.map(row => row.map(escapeCSV).join(','))
    ].join('\n');

    if (options.includeMetadata) {
        const metadata = `# Generated: ${new Date().toISOString()}\n# Confidence: ${data.confidenceScore || 0}%\n\n`;
        return metadata + csvContent;
    }

    return csvContent;
};

export const exportToHTML = async (data, options = {}) => {
    const html = `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Prescription Analysis Report</title>
    <style>
        body {
            font-family: 'Segoe UI', Arial, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 1000px;
            margin: 0 auto;
            padding: 20px;
            background: #f8f9fa;
        }
        .report-header {
            background: linear-gradient(135deg, #1976d2, #2196f3);
            color: white;
            padding: 30px;
            border-radius: 10px 10px 0 0;
            margin-bottom: 30px;
        }
        .report-title {
            font-size: 28px;
            font-weight: 600;
            margin: 0;
        }
        .report-subtitle {
            opacity: 0.9;
            margin: 5px 0 0;
        }
        .section {
            background: white;
            border-radius: 8px;
            padding: 25px;
            margin-bottom: 20px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.05);
        }
        .section-title {
            color: #1976d2;
            border-bottom: 2px solid #e3f2fd;
            padding-bottom: 10px;
            margin-bottom: 20px;
            font-size: 20px;
            display: flex;
            align-items: center;
            gap: 10px;
        }
        .medication-card {
            border-left: 4px solid #4caf50;
            padding: 15px;
            margin-bottom: 15px;
            background: #f9f9f9;
            border-radius: 0 8px 8px 0;
        }
        .warning-card {
            border-left: 4px solid #f44336;
            background: #ffebee;
        }
        .medication-name {
            font-weight: 600;
            color: #2e7d32;
            font-size: 16px;
            margin-bottom: 5px;
        }
        .dosage {
            color: #1976d2;
            margin-bottom: 5px;
        }
        .instructions {
            color: #666;
            font-style: italic;
        }
        .footer {
            text-align: center;
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #ddd;
            color: #666;
            font-size: 12px;
        }
        .confidence-badge {
            display: inline-block;
            background: ${data.confidenceScore > 90 ? '#4caf50' : data.confidenceScore > 70 ? '#ff9800' : '#f44336'};
            color: white;
            padding: 3px 10px;
            border-radius: 20px;
            font-size: 12px;
            font-weight: 600;
        }
        .metadata {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 15px;
            background: #e3f2fd;
            padding: 15px;
            border-radius: 5px;
            margin-bottom: 20px;
        }
        .metadata-item {
            display: flex;
            justify-content: space-between;
        }
        .metadata-label {
            font-weight: 600;
            color: #1976d2;
        }
        @media print {
            body { background: white; }
            .section { box-shadow: none; border: 1px solid #ddd; }
        }
    </style>
</head>
<body>
    <div class="report-header">
        <h1 class="report-title">Prescription Analysis Report</h1>
        <p class="report-subtitle">Generated: ${new Date().toLocaleDateString()}</p>
        <span class="confidence-badge">Confidence: ${data.confidenceScore || 0}%</span>
    </div>

    <div class="metadata">
        <div class="metadata-item">
            <span class="metadata-label">Report ID:</span>
            <span>${generateReportId()}</span>
        </div>
        <div class="metadata-item">
            <span class="metadata-label">Analysis Date:</span>
            <span>${new Date().toLocaleString()}</span>
        </div>
        <div class="metadata-item">
            <span class="metadata-label">Medications Found:</span>
            <span>${data.medications?.length || 0}</span>
        </div>
        <div class="metadata-item">
            <span class="metadata-label">Warnings:</span>
            <span>${data.warnings?.length || 0}</span>
        </div>
    </div>

    <div class="section">
        <h2 class="section-title">📋 Medications</h2>
        ${data.medications?.map((med, index) => `
            <div class="medication-card">
                <div class="medication-name">${med}</div>
                ${data.dosages?.[index] ? `<div class="dosage"><strong>Dosage:</strong> ${data.dosages[index]}</div>` : ''}
                ${data.instructions?.[index] ? `<div class="instructions"><strong>Instructions:</strong> ${data.instructions[index]}</div>` : ''}
            </div>
        `).join('') || '<p>No medications found.</p>'}
    </div>

    ${data.warnings?.length > 0 ? `
    <div class="section">
        <h2 class="section-title">⚠️ Warnings</h2>
        ${data.warnings.map(warning => `
            <div class="medication-card warning-card">
                ${warning}
            </div>
        `).join('')}
    </div>
    ` : ''}

    <div class="footer">
        <p>This report was generated by Prescription Interpreter Pro</p>
        <p><strong>Disclaimer:</strong> This analysis is for informational purposes only. Always consult with a qualified healthcare professional for medical advice.</p>
        <p>Report ID: ${generateReportId()} | Generated: ${new Date().toISOString()}</p>
    </div>
</body>
</html>`;

    return html;
};

export const exportToText = (data, options = {}) => {
    const lines = [];

    lines.push('='.repeat(60));
    lines.push('PRESCRIPTION ANALYSIS REPORT');
    lines.push('='.repeat(60));
    lines.push(`Generated: ${new Date().toLocaleString()}`);
    lines.push(`Report ID: ${generateReportId()}`);
    lines.push(`Confidence Score: ${data.confidenceScore || 0}%`);
    lines.push('');

    if (options.includePatientInfo) {
        lines.push('PATIENT INFORMATION');
        lines.push('-'.repeat(40));
        lines.push(`Name: ${data.patientName || 'Not specified'}`);
        lines.push(`Date: ${data.date || 'Not specified'}`);
        lines.push(`Doctor: ${data.doctor || 'Not specified'}`);
        lines.push('');
    }

    lines.push('MEDICATIONS');
    lines.push('-'.repeat(40));
    data.medications?.forEach((med, index) => {
        lines.push(`${index + 1}. ${med}`);
        if (data.dosages?.[index]) lines.push(`   Dosage: ${data.dosages[index]}`);
        if (data.instructions?.[index]) lines.push(`   Instructions: ${data.instructions[index]}`);
        lines.push('');
    });

    if (data.warnings?.length > 0) {
        lines.push('WARNINGS');
        lines.push('-'.repeat(40));
        data.warnings.forEach((warning, index) => {
            lines.push(`⚠️  ${warning}`);
        });
        lines.push('');
    }

    lines.push('='.repeat(60));
    lines.push('END OF REPORT');
    lines.push('='.repeat(60));
    lines.push('');
    lines.push('This report is generated by Prescription Interpreter Pro.');
    lines.push('For informational purposes only. Consult a healthcare professional.');

    return lines.join('\n');
};

export const generateQRCode = async (data, options = {}) => {
    const qrOptions = {
        width: options.width || 256,
        margin: 1,
        color: {
            dark: options.darkColor || '#000000',
            light: options.lightColor || '#FFFFFF'
        },
        errorCorrectionLevel: 'H'
    };

    try {
        const qrData = typeof data === 'string' ? data : JSON.stringify(data);
        return await QRCode.toDataURL(qrData, qrOptions);
    } catch (error) {
        console.error('QR Code generation failed:', error);
        throw error;
    }
};

export const exportToImage = async (elementId, options = {}) => {
    const element = document.getElementById(elementId);
    if (!element) {
        throw new Error(`Element with id "${elementId}" not found`);
    }

    const canvas = await html2canvas(element, {
        scale: options.scale || 2,
        useCORS: true,
        backgroundColor: options.backgroundColor || '#ffffff',
        logging: false,
        ...options
    });

    return new Promise((resolve) => {
        canvas.toBlob((blob) => {
            resolve(blob);
        }, 'image/png', 1.0);
    });
};

const escapeCSV = (str) => {
    if (str == null) return '';
    const string = String(str);
    if (string.includes(',') || string.includes('"') || string.includes('\n')) {
        return `"${string.replace(/"/g, '""')}"`;
    }
    return string;
};

const generateReportId = () => {
    return `RPT-${Date.now()}-${Math.random().toString(36).substr(2, 9).toUpperCase()}`;
};

export const exportFormats = {
    PDF: 'pdf',
    JSON: 'json',
    CSV: 'csv',
    HTML: 'html',
    TEXT: 'text',
    IMAGE: 'image'
};