/**
 * NMRA Sri Lankan Drug Price Dataset Converter
 * Converts the raw text dataset to structured JSON
 * Source: National Medicines Regulatory Authority (NMRA), Sri Lanka
 */

// Hand-parsed dataset from NMRA gazette - all 350 entries
// Each entry: [no, genericName, dosageForm, strength, brandName, manufacturer, marketAuthHolder, price, priceUnit]
const rawEntries = [
  [1,"Aspirin","Tablet (Delayed release)","75 mg","A PRIN 75","Ace Healthcare, Sri Lanka","Ace Healthcare, Sri Lanka",5.85,"Tablet"],
  [2,"Paclitaxel","Suspension for injection","100mg/Vial","AB-PACLI 100","Beta Drugs Ltd., India","Adora Ceylon Pvt Ltd",26332.29,"Vial"],
  [3,"Acetylcysteine","Infusion","200 mg/mL","Acetylcysteine","Mercury Laboratories, India","Yaden International",228.28,"5 mL"],
  [4,"Acetylcysteine","Infusion","200 mg/mL","Acetylcysteine","Mercury Laboratories, India","Yaden International",451.61,"10 mL"],
  [5,"Azithromycin","Tablet","500 mg","ACTISAN 500","Sands Active, Sri Lanka","Sands Active, Sri Lanka",90.00,"Tablet"],
  [6,"Adalimumab","Injection","40 mg","ADALIRED","Reliance Life Sciences, India","ABC Pharma Services",40716.00,"0.8mL Prefilled syringe"],
  [7,"Adapalene","Cream","2%","ADAPCO","Atco Laboratories, Pakistan","Morison Ltd.",787.09,"15 g"],
  [8,"Apixaban","Tablet","5 mg","ADVAXABAN","Martin Dow, Pakistan","Emerchemie NB",40.70,"Tablet"],
  [9,"Amiodarone","Tablet","100 mg","AMIDOR 100","Celogen, Sri Lanka","Celogen, Sri Lanka",38.73,"Tablet"],
  [10,"Amikacin","Injection","250mg/mL","Amikacin","Mercury Laboratories, India","Yaden International",325.00,"1mL"],
  [11,"Amikacin","Injection","250mg/mL","Amikacin","Mercury Laboratories, India","Yaden International",382.50,"2mL"],
  [12,"Amikacin","Injection","250 mg/1 mL","AMIKAN","Kelun Lifesciences, Sri Lanka","Kelun Lifesciences, Sri Lanka",373.33,"1mL"],
  [13,"Amikacin","Injection","250 mg/1 mL","AMIKAN","Kelun Lifesciences, Sri Lanka","Kelun Lifesciences, Sri Lanka",425.00,"2 mL"],
  [14,"Aminophylline","Injection","25 mg/mL","Aminophylline","Kelun Lifesciences, Sri Lanka","Kelun Lifesciences, Sri Lanka",620.00,"10 mL"],
  [15,"Amlodipine","Tablet","5 mg","AMLODAC 5","Zydus Life Sciences, India","Sunshine Healthcare",10.76,"Tablet"],
  [16,"Aripiprazole","Tablet","10 mg","ARITERO 10","Hetero Labs, India","Mansel Ceylon",44.00,"Tablet"],
  [17,"Aripiprazole","Tablet","15 mg","ARITERO 15","Hetero Labs, India","Mansel Ceylon",62.13,"Tablet"],
  [18,"Aripiprazole","Tablet","5 mg","ARITERO 5","Hetero Labs, India","Mansel Ceylon",20.72,"Tablet"],
  [19,"Atorvastatin","Tablet","10 mg","Atorvastatin","SPMC, Sri Lanka","SPMC, Sri Lanka",5.00,"Tablet"],
  [20,"Escitalopram","Tablet","5 mg","AVESTALO","Getz, Pakistan","Hemas Pharmaceuticals",23.50,"Tablet"],
  [21,"Metronidazole","Tablet","400 mg","AXCEL","Kotra Pharma, Malaysia","Sunshine Healthcare",13.83,"Tablet"],
  [22,"Azithromycin","Capsule","250 mg","AZIFRED-250","Fredun, India","George Steuart",53.00,"Capsule"],
  [23,"Azithromycin","Tablet","500 mg","AZILIDE","Micro Labs, India","Micro Healthcare",99.50,"Tablet"],
  [24,"Azithromycin","Oral suspension","200 mg/5 mL","AZITHROCIN","Beximco, Bangladesh","Emerchemie NB",347.58,"Bottle"],
  [25,"Atorvastatin","Tablet","40 mg","AZTOR 40","Sun Pharmaceutical, India","Hemas Pharmaceuticals",49.17,"Tablet"],
  [26,"Baclofen","Tablet","10 mg","BACLIN","Genome, Pakistan","Medisurge Healthcare",37.85,"Tablet"],
  [27,"Chlorhexidine Gluconate","Solution","4%","BACTOSCRUB","Raman & Weil, India","Mamro Pvt Ltd",835.67,"100 mL"],
  [28,"Chlorhexidine Gluconate","Solution","4%","BACTOSCRUB","Raman & Weil, India","Mamro Pvt Ltd",2793.38,"500 mL"],
  [29,"Chlorhexidine Gluconate","Solution","4%","BACTOSCRUB","Raman & Weil, India","Mamro Pvt Ltd",18074.19,"5 L"],
  [30,"Cefotaxime","Injection","1 g","BAXIM-1","Nabiquasim, Pakistan","George Steuart",456.07,"Vial"],
  [31,"Abiraterone","Tablet","500 mg","BDRON","BDR Pharmaceuticals, India","Pharma Associates",2109.15,"Tablet"],
  [32,"Beclomethasone","Inhalation Capsules","400 mcg","BECLOHALE","Emergen, Sri Lanka","Emergen, Sri Lanka",10.92,"Capsule"],
  [33,"Clobetasol","Cream","0.05%","BELTAPRO CREAM","Tabros Pharma, Pakistan","Associated Laboratories",397.90,"15g tube"],
  [34,"Clobetasol","Cream","0.05%","BELTAPRO CREAM","Tabros Pharma, Pakistan","Associated Laboratories",176.00,"5g tube"],
  [35,"Bendamustine","Injection","100 mg","BENDAWEL","Getwell Pharma, India","Esses Pharmacy",24500.00,"Vial"],
  [36,"Benzoyl Peroxide","Gel","5%","BENOX 5 GEL","East African, India","Mega Pharma",650.00,"20 g"],
  [37,"Betahistine","Tablet","16 mg","BETAGEN 16","Newgen, Sri Lanka","Newgen, Sri Lanka",28.90,"Tablet"],
  [38,"Betamethasone","Eye/Ear drops","0.10%","BETANIN","Sunway Rohto, India","Yaden International",342.00,"5 mL"],
  [39,"Betahistine","Tablet","8 mg","BETASTIN 8","Corona Remedies, India","Sunshine Healthcare",10.47,"Tablet"],
  [40,"Sterile Cardioplagia solution","Infusion","20 mL","BIOPLAGIA","United Biotech, India","Klintas (Pvt) Ltd.",868.72,"Vial"],
  [41,"Bisoprolol","Tablet","2.5 mg","BISOPRACE 2.5","Ace Healthcare, Sri Lanka","Ace Healthcare, Sri Lanka",27.00,"Tablet"],
  [42,"Budesonide","Nebulizer Suspension","0.5 mg/2 mL","BUDEZ 0.5","Sun Pharmaceutical, India","Hemas Pharmaceuticals",326.40,"Ampoule"],
  [43,"Cholecalciferol","Tablet (chewable)","60,000 IU","CAD D 60000","Finecure, India","Bio Life",131.47,"Tablet"],
  [44,"Cholecalciferol","Tablet (chewable)","400 IU","CALMIT-400IU","MMC Healthcare, India","Markss HLC",25.00,"Tablet"],
  [45,"Clotrimazole","Cream","1%","CANBEN","Leben, India","Ceyoka (Pvt) Ltd.",203.00,"15 g"],
  [46,"Capecitabine","Tablet","500 mg","CAPETERO 500","Hetero Labs, India","Mansel Ceylon",395.00,"Tablet"],
  [47,"Carbamazepine","Tablet","100 mg","Carbamazepine","Sands Active, Sri Lanka","Sands Active, Sri Lanka",15.00,"Tablet"],
  [48,"Carbimazole","Tablet","5 mg","CARBIMOLE 5","Newgen, Sri Lanka","Newgen, Sri Lanka",11.25,"Tablet"],
  [49,"Carvedilol","Tablet","6.25 mg","CARDIACT 6.25","Sands Active, Sri Lanka","Sands Active, Sri Lanka",12.29,"Tablet"],
  [50,"Aspirin","Tablet","300 mg","CAREPRIN 300","Celogen, Sri Lanka","Celogen, Sri Lanka",4.00,"Tablet"],
  [51,"Cefuroxime","Tablet","125 mg","CEFERO 125","Zim Laboratories, India","Tabrane Pharmaceuticals",50.00,"Tablet"],
  [52,"Metformin","Tablet","1000 mg","CELOMET 1000","Celogen, Sri Lanka","Celogen, Sri Lanka",14.50,"Tablet"],
  [53,"Diclofenac Sodium","Tablet (gastro-resistant)","100 mg","CELONAC 100","Celogen, Sri Lanka","Celogen, Sri Lanka",30.00,"Tablet"],
  [54,"Gemcitabine","Injection","200 mg","CELZAR","Celon Laboratories, India","Medmart Pharma",2918.00,"Vial"],
  [55,"Cefixime","Tablet","200 mg","CFIXM-200","Sands Active, Sri Lanka","Sands Active, Sri Lanka",84.81,"Tablet"],
  [56,"Cisatracurium Besylate","Injection","10mg/5mL","CISATRA","Themis Medicare, India","Sunshine Healthcare",2610.38,"Vial"],
  [57,"Clindamycin","Capsule","150 mg","Clindamycin","Gamma Interpharm, Sri Lanka","Gamma Interpharm, Sri Lanka",48.30,"Capsule"],
  [58,"Clobazam","Tablet","10 mg","Clobazam","Celogen, Sri Lanka","Celogen, Sri Lanka",18.00,"Tablet"],
  [59,"Clopidogrel","Tablet","75 mg","CLOPEX","Astron, Sri Lanka","Astron, Sri Lanka",14.00,"Tablet"],
  [60,"Hydrocortisone","Injection","100 mg","CORTEC 100","United Biotech, India","Klintas (Pvt) Ltd.",250.94,"Vial"],
  [61,"Clobetasol","Ointment","0.05%","COSVATE","Blossom, India","George Steuart",374.42,"15g tube"],
  [62,"Dabigatran","Capsule","110 mg","DABRINEX 110","Hetero Labs, India","Mansel Ceylon",165.00,"Capsule"],
  [63,"Terbinafine","Tablet","250 mg","DERBIFIN 250","Bharat Parenterals, India","Baur Life Science",68.60,"Tablet"],
  [64,"Darbepoetin Alfa","Injection","25 mcg/0.42 mL","DERISE 25","Hetero Drugs, India","Divasa Pharma",7020.00,"Pre-filled syringe"],
  [65,"Cholecalciferol","Capsule","10,000 IU","DEUP 10K","Celogen, Sri Lanka","Celogen, Sri Lanka",190.00,"Capsule"],
  [66,"Dexmedetomidine","Injection","200 mcg/2 mL","Dexmedetomidine","Kelun Lifesciences, Sri Lanka","Kelun Lifesciences, Sri Lanka",3853.98,"Ampoule"],
  [67,"Metformin","Tablet","850 mg","DIAMET 850","Sands Active, Sri Lanka","Sands Active, Sri Lanka",9.57,"Tablet"],
  [68,"Aceclofenac","Tablet (sustained release)","200 mg","DOLOWIN SR","Micro Labs, India","Micro Healthcare",31.50,"Tablet"],
  [69,"Dopamine","Injection","200 mg/5 mL","DOPRESS-200","United Biotech, India","Klintas (Pvt) Ltd.",157.36,"Ampoule"],
  [70,"Doxycycline","Capsule","100 mg","Doxycycline","Dagon Pharmaceuticals, India","Eurochem Biotech",20.00,"Capsule"],
  [71,"Duloxetine","Capsule (delayed release)","60 mg","DULOX 60","Zim Laboratories, India","Tabrane Pharmaceuticals",72.00,"Capsule"],
  [72,"Ipratropium bromide + Salbutamol","Respirator solution","500 mcg + 2.5 mg/2.5 mL","DUOLIN RESPULES","Cipla Ltd., India","Breathe Free",81.39,"Vial"],
  [73,"Cholecalciferol","Capsule","60,000 IU","DV 60K","Indchemie, India","Pharma Associates",150.00,"Capsule"],
  [74,"Cefixime","Oral suspension","100 mg/5 mL","ECOCEF 100","Indchemie, India","Pharma Associates",685.25,"100 mL bottle"],
  [75,"Efavirenz","Tablet","200 mg","EFIREN-200","Celogen, Sri Lanka","Celogen, Sri Lanka",192.45,"Tablet"],
  [76,"Efavirenz","Tablet","600 mg","EFIREN-600","Celogen, Sri Lanka","Celogen, Sri Lanka",560.00,"Tablet"],
  [77,"Esomeprazole","Tablet","20 mg","EMA-20","Globe, Bangladesh","Tabrane Healthcare",15.00,"Tablet"],
  [78,"Empagliflozin","Tablet","25 mg","EMPIRE 25","Drug International, Bangladesh","Amsted Intima (Pvt) Ltd",139.38,"Tablet"],
  [79,"Eplerenone","Tablet","25 mg","EPNONE 25","MSN Laboratories, India","Axia Pvt Ltd",100.31,"Tablet"],
  [80,"Etomidate","Injection","20 mg/10 mL","Etomidate","Mercury Laboratories, India","Yaden International",1740.00,"10 mL"],
  [81,"Etomidate","Injection","20 mg/10 mL","ETUDAT","Kelun Lifesciences, Sri Lanka","Kelun Lifesciences, Sri Lanka",2227.20,"10 mL"],
  [82,"Cefixime","Tablet (dispersible)","100 mg","EXTACEF 100 DT","Blue Cross, India","Sunshine Healthcare",39.09,"Tablet"],
  [83,"Famotidine","Tablet","20 mg","FAMTIN 20","Celogen, Sri Lanka","Celogen, Sri Lanka",11.38,"Tablet"],
  [84,"Medroxyprogesterone","Injection","150 mg/mL","FAMY-DEPO","Mylan, India","Baur & Co.",465.14,"1 mL"],
  [85,"Fat Emulsion + Amino Acid","Infusion","20% + 11%","Fat Emulsion + Amino Acid","Sichuan Kelun, India","Pharma Associates",14979.00,"1440 mL"],
  [86,"Cefalexin","Capsule","250 mg","FAXIN-250","Sands Active, Sri Lanka","Sands Active, Sri Lanka",15.10,"Capsule"],
  [87,"Formoterol + Fluticasone","Inhaler (metered dose)","5 mcg + 125 mcg/dose","FLIMYST 5/125","Beximco, Bangladesh","Emerchemie NB",1665.76,"Canister"],
  [88,"Ofloxacin","Eye drops","0.30%","FLOBOID","Micro Labs, India","Micro Healthcare",192.00,"5 mL"],
  [89,"Fluconazole","Capsule","150 mg","FLUCAST 150","McW Healthcare, India","Innogen Lanka",67.00,"Capsule"],
  [90,"Flumazenil","Injection","500 mcg/5 mL","Flumazenil","Mercury Laboratories, India","Yaden International",7230.98,"5 mL"],
  [91,"Fluticasone","Pressurized inhalation","50 mcg/dose","Fluticasone","Heilongjiang, China","Ceyoka (Pvt) Ltd.",2062.50,"Canister"],
  [92,"Formoterol + Budesonide","Inhalation capsule","6 mcg + 400 mcg","FORMONIDE 400","Lina Manufacturing, Sri Lanka","Lina Manufacturing, Sri Lanka",43.00,"Capsule"],
  [93,"Framycetin sulfate","Cream","1%","FRAMICIN","Nem Laboratories, India","Softlogic Pharmaceuticals",177.35,"20 g"],
  [94,"Fusidic acid","Ointment","2%","FUSITOP","Aurochem Laboratories, India","Slim Pharmaceutical",839.77,"15 g"],
  [95,"Gabapentin","Capsule","100 mg","GABALEPT 100","Micro Labs, India","Micro Mega",31.37,"Capsule"],
  [96,"Sitagliptin","Tablet","100 mg","GENSITA 100","Newgen, Sri Lanka","Newgen, Sri Lanka",57.00,"Tablet"],
  [97,"Sitagliptin","Tablet","50 mg","GENSITA 50","Newgen, Sri Lanka","Newgen, Sri Lanka",32.50,"Tablet"],
  [98,"Glimepiride","Tablet","1 mg","GLIMPIR 1","Celogen, Sri Lanka","Celogen, Sri Lanka",12.00,"Tablet"],
  [99,"Amphotericin B liposomal","Injection","50 mg","GUFISOME","Gufic, India","Slim Pharmaceutical",34425.02,"Vial"],
  [100,"Methotrexate","Injection","50mg/2 mL","HI TREX-PF","VHB, India","Yaden International",820.00,"2 mL"],
  [101,"Multivitamin","Syrup","-","HOVITE","Raptakos Brett, India","Pharma Associates",188.58,"45 mL"],
  [102,"Multivitamin","Syrup","-","HOVITE","Raptakos Brett, India","Pharma Associates",506.20,"120 mL"],
  [103,"Hydralazine","Injection","20 mg/mL","Hydralazine","Ciron Drugs, India","Ceyoka (Pvt) Ltd.",2067.56,"1 mL"],
  [104,"Hydrocortisone","Injection","100 mg","HYDROCORT 100","Belco Pharma, India","Pharmatec (Pvt) Ltd.",286.00,"Vial"],
  [105,"Hydrocortisone","Injection","100 mg","Hydrocortisone","Ciron Drugs, India","Ceyoka (Pvt) Ltd.",263.92,"5 mL"],
  [106,"Hydroxocobalamin","Injection","1 mg/mL","Hydroxocobalamin","Mercury Laboratories, India","Yaden International",315.00,"1 mL Ampoule"],
  [107,"Immunoglobulin","Solution for Infusion","50 g/L","IG VENA","Kedrion S.p.A, Italy","Slim Pharmaceutical",245760.50,"200 mL vial"],
  [108,"Immunoglobulin","Solution for Infusion","50 g/L","IG VENA","Kedrion S.p.A, Italy","Slim Pharmaceutical",122880.25,"100 mL vial"],
  [109,"Immunoglobulin","Solution for Infusion","50 g/L","IG VENA","Kedrion S.p.A, Italy","Slim Pharmaceutical",61440.12,"50 mL vial"],
  [110,"Human Coagulation Factor VIII","Injection","250 IU","IMMUNATE","Takeda, Austria","A.J. Medichem",17478.88,"Vial"],
  [111,"Influenza vaccine","Injection","15 mcg/0.5 mL","INFLUVAC","Abbot Biologicals, Netherlands","Sunshine Healthcare",3096.00,"Pre-filled syringe"],
  [112,"Irinotecan","Injection","100 mg/5 mL","Irinotecan","Getwell Pharma, India","Esses Pharmacy",10487.33,"Vial"],
  [113,"Iohexol","Injection","350 mg I/mL","JODASCAN 350","Jodas Expoim, India","Softcare International",980.56,"20 mL vial"],
  [114,"Iohexol","Injection","350 mg I/mL","JODASCAN 350","Jodas Expoim, India","Softcare International",2451.40,"50 mL vial"],
  [115,"Iohexol","Injection","350 mg I/mL","JODASCAN 350","Jodas Expoim, India","Softcare International",3454.25,"75 mL vial"],
  [116,"Iohexol","Injection","350 mg I/mL","JODASCAN 350","Jodas Expoim, India","Softcare International",4605.68,"100 mL vial"],
  [117,"Everolimus","Tablet","0.25 mg","JOELIMUS 0.25","Jodas Expoim, India","Softcare International",572.00,"Tablet"],
  [118,"Levetiracetam","Tablet (extended release)","750 mg","JULITAM XR","Celogen, Sri Lanka","Celogen, Sri Lanka",125.23,"Tablet"],
  [119,"Calcium + Cholecalciferol","Tablet (chewable)","500 mg + 400 IU","KACO-D 500","Gamma Interpharm, Sri Lanka","Gamma Interpharm, Sri Lanka",22.67,"Tablet"],
  [120,"Cefuroxime","Injection","750 mg","KALCEF","Zhuhai, China","Hemas Pharmaceuticals",640.00,"Vial"],
  [121,"Cefalexin","Oral suspension","125 mg/5 mL","KEPHALEX B","Bharat Parenterals, India","Baur Life Science",354.20,"100 mL"],
  [122,"Phytomenadione","Injection","1 mg/0.5 mL","K-VIT 1","Kelun Lifesciences, Sri Lanka","Kelun Lifesciences, Sri Lanka",350.00,"0.5 mL"],
  [123,"Lamotrigine","Tablet","50 mg","LAMITOR 50","Torrent, India","Hemas Pharmaceuticals",29.66,"Tablet"],
  [124,"Levocetirizine","Tablet","5 mg","LECET","Genome, Pakistan","Medisurge Healthcare",18.85,"Tablet"],
  [125,"Lamivudine","Tablet","150 mg","LEMIVIR","Celogen, Sri Lanka","Celogen, Sri Lanka",180.80,"Tablet"],
  [126,"Leucovorin calcium","Injection","15 mg/2 mL","LEUCOWEL","Getwell Pharma, India","Esses Pharmacy",446.64,"Ampoule"],
  [127,"Levetiracetam","Tablet","750 mg","LEVETAM 750","Newgen, Sri Lanka","Newgen, Sri Lanka",90.00,"Tablet"],
  [128,"Lidocaine","Injection","2%","LICAN","Kelun Lifesciences, Sri Lanka","Kelun Lifesciences, Sri Lanka",180.00,"5mL"],
  [129,"Lidocaine","Injection","2%","LICAN","Kelun Lifesciences, Sri Lanka","Kelun Lifesciences, Sri Lanka",194.40,"20mL"],
  [130,"Lidocaine","Injection","2%","Lidocaine","Yaden Laboratories, Sri Lanka","Yaden Laboratories, Sri Lanka",180.00,"5 mL"],
  [131,"Lidocaine","Injection","2%","Lidocaine","Yaden Laboratories, Sri Lanka","Yaden Laboratories, Sri Lanka",194.40,"20 mL"],
  [132,"Lidocaine","Injection","2%","Lidocaine","Mercury Laboratories, India","Yaden International",150.00,"5mL"],
  [133,"Lidocaine","Injection","2%","Lidocaine","Pharmafabrikon, India","Novachem Lanka",99.87,"5 mL"],
  [134,"Lidocaine","Injection","2%","Lidocaine","Pharmafabrikon, India","Novachem Lanka",149.82,"20 mL"],
  [135,"Lidocaine","Injection","2%","Lidocaine","Pharmafabrikon, India","Novachem Lanka",220.00,"30 mL"],
  [136,"Linezolid","Injection","600 mg/300 mL","LINZO-R","ER. K. Laboratories, India","PTC Medical",2184.35,"Ampoule"],
  [137,"Atorvastatin","Tablet","10 mg","LIPITOR","Pfizer, Germany","Hemas Pharmaceuticals",22.10,"Tablet"],
  [138,"Loratadine","Oral Solution","5 mg/5mL","LORID","Unique Pharmaceuticals, India","George Steuart Health",416.00,"60mL"],
  [139,"Meloxicam","Tablet","7.5 mg","LOXINOL 7.5","Agio Pharmaceuticals, India","Citihealth Imports",8.00,"Tablet"],
  [140,"Losartan","Tablet","25 mg","LOZART","Astron, Sri Lanka","Astron, Sri Lanka",8.00,"Tablet"],
  [141,"Leuprolide","Injection (depot)","3.75 mg","LUPROVA 3.75","Celon Laboratories, India","Medmart Pharma",10924.30,"Vial"],
  [142,"Mitomycin","Injection","2 mg","LYOMIT 2","United Biotech, India","Klintas (Pvt) Ltd.",1600.00,"5 mL Vial"],
  [143,"Magnesium sulphate","Injection","50%","MAGCI-50","Ciron Drugs, India","Ceyoka (Pvt) Ltd.",30.40,"1mL"],
  [144,"Magnesium sulphate","Injection","50%","MAGCI-50","Ciron Drugs, India","Ceyoka (Pvt) Ltd.",100.32,"2mL"],
  [145,"Magnesium sulphate","Injection","50%","MAGCI-50","Ciron Drugs, India","Ceyoka (Pvt) Ltd.",304.00,"10mL"],
  [146,"Oxytocin","Injection","5 IU/1 mL","MARITON","Chengdu Hepatunn, China","Slim Pharmaceutical",431.75,"Ampoule"],
  [147,"Mefenamic acid","Tablet","500 mg","MEFTAL 500","Blue Cross Laboratories, India","Sunshine Healthcare",16.87,"Tablet"],
  [148,"Multivitamin and Minerals","Tablet","-","MEGAVIT","The Acme, Bangladesh","Mega Pharma",55.00,"Tablet"],
  [149,"Cefepime","Injection","500 mg","MELPIN 500","Sands Active, Sri Lanka","Sands Active, Sri Lanka",795.00,"10 mL"],
  [150,"Sitagliptin","Tablet","25 mg","MELSITA 25","Sands Active, Sri Lanka","Sands Active, Sri Lanka",28.37,"Tablet"],
  [151,"Meropenem","Injection","1g","MEROFIC 1G","Gufic, India","Slim Pharmaceutical",7661.75,"Vial"],
  [152,"Aceclofenac","Tablet","100 mg","MERVAN","Aristopharma, Bangladesh","Hemas Pharmaceuticals",20.47,"Tablet"],
  [153,"Mesna","Injection","200 mg/2 mL","Mesna","Getwell Pharma, India","Esses Pharmacy",543.97,"Ampoule"],
  [154,"Methylphenidate","Tablet","10 mg","METHYPHEN","Celogen, Sri Lanka","Celogen, Sri Lanka",40.00,"Tablet"],
  [155,"Metoclopramide","Tablet","10 mg","Metoclopramide","Mercury Laboratories, India","Yaden International",7.00,"Tablet"],
  [156,"Metoclopramide","Injection","10 mg/2 mL","Metoclopramide","Mercury Laboratories, India","Yaden International",98.00,"2 mL"],
  [157,"Milrinone","Injection","1 mg/1 mL","MIRONE","Kelun Lifescience, Sri Lanka","Kelun Lifescience, Sri Lanka",3150.00,"1 mL"],
  [158,"Telmisartan","Tablet","20 mg","MISAR 20","Highnoon, Pakistan","Truvic (Pvt) Ltd.",20.00,"Tablet"],
  [159,"Montelukast","Tablet (chewable)","5 mg","MOTELAST 5","Cadila Pharmaceuticals, India","Sunshine Healthcare",11.00,"Tablet"],
  [160,"Mycophenolate","Tablet (gastro-resistant)","180 mg","MYFORTIC 180MG","Novartis, Switzerland","Baur & Co.",277.56,"Tablet"],
  [161,"Mycophenolate","Tablet (delayed release)","360 mg","MYOTEC-S 360","United Biotech, India","Klintas (Pvt) Ltd.",355.00,"Tablet"],
  [162,"Midazolam","Injection","5mg/mL","Midazolam","Ciron Drugs, India","Ceyoka (Pvt) Ltd.",356.25,"1 mL"],
  [163,"Sodium chloride","Nasal spray","0.65%","NASOCLEAR","Zydus Life Sciences, India","Gamma Interpharm",154.82,"Pack"],
  [164,"Diclofenac potassium","Tablet","50 mg","NEODOL-K","Micro Healthcare, India","Micro Healthcare",16.50,"Tablet"],
  [165,"Cyclophosphamide","Injection","200 mg","NEOPHOS","Drug International, Bangladesh","Tabrane Pharmaceuticals",608.99,"Vial"],
  [166,"Etanercept","Injection (Prefilled syringe)","50 mg/1 mL","NEPEXTO","Lupin, India","Ceyoka (Pvt) Ltd.",30950.00,"0.5 mL syringe"],
  [167,"Etanercept","Injection (Prefilled syringe)","50 mg/1 mL","NEPEXTO","Lupin, India","Ceyoka (Pvt) Ltd.",52000.00,"1.0 mL syringe"],
  [168,"Etanercept","Injection (Prefilled pen)","50 mg/1 mL","NEPEXTO","Lupin, India","Ceyoka (Pvt) Ltd.",55000.00,"Pre-filled pen"],
  [169,"Filgrastim","Injection","300mcg/mL","NEUTROFLX","Kexing Biopharma, China","Slim Pharmaceutical",5145.39,"Pre-filled syringe"],
  [170,"Nilotinib","Capsule","150 mg","NILTIB 150","Hetero Labs, India","Mansel Ceylon",1100.00,"Capsule"],
  [171,"Nimodipine","Infusion","10 mg/50 mL","NIMODEC","United Biotech, India","Klintas (Pvt) Ltd.",4100.38,"50 mL Vial"],
  [172,"Ciprofloxacin","Infusion","200 mg/100 mL","NIRCIP","Aculife Healthcare, India","Emerchemie NB",153.84,"Vial"],
  [173,"Thiamine hydrochloride","Injection","100 mg/2 mL","ONE B","Kelun Lifescience, Sri Lanka","Kelun Lifescience, Sri Lanka",250.00,"2 mL"],
  [174,"Fentanyl","Injection","100 mcg/2 mL","OPNIL","Kelun Lifescience, Sri Lanka","Kelun Lifescience, Sri Lanka",340.00,"2 mL"],
  [175,"Carboxymethylcellulose + Glycerin","Eye drops","0.5% + 0.9%","OPTIVE","Allergan LLC, USA","Hemas Pharmaceuticals",1476.00,"15 mL Vial"],
  [176,"Loratadine","Suspension","5 mg/5mL","Oradin","Eskayef Bangladesh","Truvic Private Ltd",431.00,"60mL"],
  [177,"Hyoscine butylbromide","Tablet","10 mg","OROSPAS","Macleods, India","Emerchemie NB",27.19,"Tablet"],
  [178,"Protamine Sulphate","Injection","50mg/5 mL","ORVOPROT 50","United Biotech, India","Klintas (Pvt) Ltd.",1370.50,"Ampoule"],
  [179,"Oseltamivir","Capsule","45 mg","Oseltamivir","Sands Active, Sri Lanka","Sands Active, Sri Lanka",488.55,"Capsule"],
  [180,"Octreotide","Injection","50 mcg/mL","OTIDE","United Biotech, India","Klintas (Pvt) Ltd.",1393.00,"Vial"],
  [181,"Pantoprazole","Tablet (delayed release)","20 mg","PANTO DR 20","Newgen, Sri Lanka","Newgen, Sri Lanka",25.00,"Tablet"],
  [182,"Paracetamol","Tablet","500 mg","PARAMOL 500","Newgen, Sri Lanka","Newgen, Sri Lanka",3.20,"Tablet"],
  [183,"Enoxaparin","Injection","40 mg/0.4 mL","PARIN-E","Venus Remedies, India","Yaden International",2635.00,"Pre-filled syringe"],
  [184,"Pemetrexed","Injection","100 mg","PEMETRA 100","Getwell Pharma, India","Esses Pharmacy",5605.30,"Vial"],
  [185,"Phenylephrine","Injection","10 mg/mL","PHERAN","Kelun Lifescience, Sri Lanka","Kelun Lifescience, Sri Lanka",2311.52,"Vial"],
  [186,"Phenylephrine","Injection","10 mg/mL","PHRINTEC","United Biotech, India","Klintas (Pvt) Ltd.",1955.00,"Ampoule"],
  [187,"Piroxicam","Gel","0.50%","PICAM GEL","Micro Labs, India","Micro Healthcare",475.00,"30 g"],
  [188,"Cefepime","Injection","1 g","PIMECEF 1G","Surge Laboratories, Pakistan","George Steuart",1023.78,"Vial"],
  [189,"Cefepime","Injection","500 mg","PIMECEF 500","Surge Laboratories, Pakistan","George Steuart",588.23,"Vial"],
  [190,"Pneumococcal Vaccine","Injection","10 valent","PCV-10","Serum Institute, India","Citihealth Imports",14779.00,"5 dose vial"],
  [191,"Poliomyelitis vaccine","Oral drops","-","Polio Vaccine","Panacea Biotec, India","Baur & Co.",690.39,"10 dose vial"],
  [192,"Poliomyelitis vaccine","Oral drops","-","Polio Vaccine","Panacea Biotec, India","Baur & Co.",1380.78,"20 dose vial"],
  [193,"Pramipexole","Tablet","0.25 mg","PRAMIZ 0.25","Zydus Life Sciences, India","Zydus Lanka",44.00,"Tablet"],
  [194,"Human Normal Immunoglobulin","Infusion","100g/1000mL","PRIVIGEN","CSL Behring, Switzerland","ABC Pharma Services",491521.00,"200 mL"],
  [195,"Human Normal Immunoglobulin","Infusion","100g/1000mL","PRIVIGEN","CSL Behring, Switzerland","ABC Pharma Services",245760.50,"100mL"],
  [196,"Human Normal Immunoglobulin","Infusion","100g/1000mL","PRIVIGEN","CSL Behring, Switzerland","ABC Pharma Services",122880.25,"50mL"],
  [197,"Human Normal Immunoglobulin","Infusion","100g/1000mL","PRIVIGEN","CSL Behring, Switzerland","ABC Pharma Services",61440.00,"25 mL"],
  [198,"Promethazine","Oral solution","5 mg/5 mL","PROMACE","Ace Healthcare, Sri Lanka","Ace Healthcare, Sri Lanka",135.00,"100 mL"],
  [199,"Promethazine","Oral solution","5 mg/5 mL","PROMACE","Ace Healthcare, Sri Lanka","Ace Healthcare, Sri Lanka",550.00,"500 mL"],
  [200,"Promethazine","Injection","25 mg/mL","Promethazine","Yaden Laboratories, Sri Lanka","Yaden Laboratories, Sri Lanka",179.02,"1mL"],
  [201,"Promethazine","Injection","25 mg/mL","Promethazine","Yaden Laboratories, Sri Lanka","Yaden Laboratories, Sri Lanka",330.00,"2 mL"],
  [202,"Glucose","Infusion","10%","R DEX-D10","R.K. Laboratories, India","PTC Medical",270.00,"500mL"],
  [203,"Ranitidine","Injection","25 mg/mL","RANITID","Sakar Healthcare, India","Ceyoka (Pvt) Ltd.",111.46,"2 mL"],
  [204,"Diazepam","Injection","5 mg/mL","RELIVIUM","HBM Pharma, Latvia","Baur Life Science",500.19,"2 mL"],
  [205,"Infliximab","Injection","120 mg","REMSIMA SC","Celtrion, Korea","George Steuart",207599.30,"Pack of 2 syringes"],
  [206,"Infliximab","Injection","120 mg","REMSIMA SC","Celtrion, Korea","George Steuart",103799.65,"Pack of 1 syringe"],
  [207,"Risperidone","Tablet","2 mg","RESICALM 2","Aurobindo Pharma, India","Alaris Lanka",15.32,"Tablet"],
  [208,"Risperidone","Tablet","1 mg","RESPIGEN 1","Newgen, Sri Lanka","Newgen, Sri Lanka",9.00,"Tablet"],
  [209,"Deferiprone","Tablet","500 mg","RIPRONE 500","Genome, Pakistan","Slim Pharmaceutical",112.45,"Tablet"],
  [210,"Risperidone","Tablet","2 mg","Risperidone","Sands Active, Sri Lanka","Sands Active, Sri Lanka",18.20,"Tablet"],
  [211,"Rizatriptan","Tablet","5 mg","RIZY 5","Celogen, Sri Lanka","Celogen, Sri Lanka",120.00,"Tablet"],
  [212,"Meropenem","Injection","500 mg","RONEM","Venus Remedies, India","Ceyoka (Pvt) Ltd.",4396.50,"Vial"],
  [213,"Rosuvastatin","Tablet","10 mg","ROSUKE 10","Finecure, India","Bio Life",54.00,"Tablet"],
  [214,"Rosuvastatin","Tablet","5 mg","Rosuvastatin","Sands Active, Sri Lanka","Sands Active, Sri Lanka",42.00,"Tablet"],
  [215,"Sodium chloride","Infusion","0.90%","R-SALINE NS","R.K. Laboratories, India","PTC Medical",206.40,"500mL"],
  [216,"Rupatadine","Tablet","10 mg","RUPADAY","Eskayef, Bangladesh","Truvic (Pvt) Ltd.",42.00,"Tablet"],
  [217,"Coagulation Factor VIII","Injection","500 IU","SAFACTO AF","Saman Daroo, Iran","Cliniqon Biotech",34681.56,"Vial"],
  [218,"Coagulation Factor VIII","Injection","250 IU","SAFACTO AF","Saman Daroo, Iran","Cliniqon Biotech",17340.78,"Vial"],
  [219,"Somatropin","Injection","5.83 mg/mL","SAIZEN LIQUID","Merck Serono, Italy","Baur & Co.",38322.44,"Pre-filled syringe"],
  [220,"Salbutamol","Oral solution","2 mg/5 mL","Salbutamol","Diyatha, Sri Lanka","Diyatha, Sri Lanka",222.00,"60 mL"],
  [221,"Salbutamol","Oral solution","2 mg/5 mL","Salbutamol","Diyatha, Sri Lanka","Diyatha, Sri Lanka",371.00,"100 mL"],
  [222,"Salbutamol","Oral solution","2 mg/5 mL","Salbutamol","Diyatha, Sri Lanka","Diyatha, Sri Lanka",800.00,"500 mL"],
  [223,"Salbutamol","Oral solution","2 mg/5 mL","Salbutamol","Diyatha, Sri Lanka","Diyatha, Sri Lanka",1110.00,"750 mL"],
  [224,"Salbutamol","Pressurized Inhalation","200 mcg/dose","SALBUVENT 200","Lina Spiro, Sri Lanka","Lina Spiro, Sri Lanka",1460.00,"Inhaler"],
  [225,"Risperidone","Tablet","2 mg","SANDONE 2","Sands Active, Sri Lanka","Sands Active, Sri Lanka",17.50,"Tablet"],
  [226,"Sevoflurane","Inhalation Liquid","-","Sevoflurane","Shandong, China","Gulf Pharma",38850.00,"Bottle"],
  [227,"Cefuroxime","Injection","250mg","SHAMCEF 250","Shamshree, India","Omacx Healthcare",452.00,"Vial"],
  [228,"Sildenafil","Tablet","20 mg","SILATIO","Unison, Thailand","Sunshine Healthcare",41.81,"Tablet"],
  [229,"Sildenafil","Tablet","50 mg","Sildenafil","Celogen, Sri Lanka","Celogen, Sri Lanka",133.20,"Tablet"],
  [230,"Basiliximab","Injection","20 mg","SIMULECT","Novartis, Switzerland","Baur & Co.",275000.00,"Vial"],
  [231,"Sitagliptin","Tablet","100 mg","Sitagliptin","Sands Active, Sri Lanka","Sands Active, Sri Lanka",85.32,"Tablet"],
  [232,"Sitagliptin","Tablet","50 mg","SITAGLYN 50","Celogen, Sri Lanka","Celogen, Sri Lanka",48.01,"Tablet"],
  [233,"Isotretinoin","Capsule","10 mg","SOTRET","Sun Pharmaceutical, India","Emerchemie NB",138.07,"Capsule"],
  [234,"Succinylcholine","Injection","50 mg/mL","SUXONIUM","Kelun Lifescience, Sri Lanka","Kelun Lifescience, Sri Lanka",357.59,"2 mL"],
  [235,"Tamsulosin","Capsule","0.4 mg","TALMOSIN","Ace Healthcare, Sri Lanka","Ace Healthcare, Sri Lanka",37.00,"Capsule"],
  [236,"Tamsulosin","Capsule","0.4 mg","Tamsulosin","Ace Healthcare, Sri Lanka","Ace Healthcare, Sri Lanka",37.00,"Capsule"],
  [237,"Cefotaxime","Injection","500 mg","TAXOVENT 500","Innova, India","Cliniqon Biotech",425.64,"Vial"],
  [238,"Teicoplanin","Injection","200 mg","TECOPLAN 200","United Biotech, India","Klintas (Pvt) Ltd.",4850.00,"Vial"],
  [239,"Teicoplanin","Injection","400 mg","TECOPLAN 400","United Biotech, India","Klintas (Pvt) Ltd.",8800.00,"Vial"],
  [240,"Terbinafine","Gel","1.12%","TEFIN","HOE, Malaysia","Indoscan (Pvt) Ltd.",587.54,"15 g Tube"],
  [241,"Carbamazepine","Tablet (controlled release)","200 mg","TEGRETOL CR 200","Novartis, Switzerland","Baur & Co.",47.46,"Tablet"],
  [242,"Telmisartan","Tablet","40 mg","TELGIO 40","PT Dexa Medica, Indonesia","Baur & Co.",26.32,"Tablet"],
  [243,"Tetracycline","Capsule","250 mg","TETRET 250","Leben, India","Ceyoka (Pvt) Ltd.",5.98,"Capsule"],
  [244,"Theophylline","Capsule (controlled release)","200 mg","Theophylline","Raptakos Brett, India","Pharma Associates",6.43,"Capsule"],
  [245,"Azathioprine","Tablet","50 mg","THIOPRESS 50","United Biotech, India","Klintas (Pvt) Ltd.",59.00,"Tablet"],
  [246,"Levothyroxine","Tablet","50 mcg","THYRIN 50","Square, Bangladesh","CIC Holdings",10.67,"Tablet"],
  [247,"Thyroxine","Tablet","25 mcg","THYROX 25","Macleods, India","Emerchemie NB",11.51,"Tablet"],
  [248,"Ticagrelor","Tablet","90 mg","TICACARD 90","Aristopharma, Bangladesh","Hemas Pharmaceuticals",113.00,"Tablet"],
  [249,"Topiramate","Tablet","25 mg","TOPIRA 25","Celogen, Sri Lanka","Celogen, Sri Lanka",24.00,"Tablet"],
  [250,"Topiramate","Tablet","50 mg","TOPIRA 50","Celogen, Sri Lanka","Celogen, Sri Lanka",46.00,"Tablet"],
  [251,"Ketorolac","Injection","30 mg/mL","TORADOL","Martin Dow, Pakistan","Emerchemie NB",290.81,"Ampoule"],
  [252,"Torasemide","Tablet","10 mg","TORAS-DENK 10","Denk Pharma, Germany","Sunshine Healthcare",63.17,"Tablet"],
  [253,"Terlipressin","Injection","1 mg/10 mL","T-PRESSIN","United Biotech, India","Klintas (Pvt) Ltd.",5984.55,"Ampoule"],
  [254,"Ceftriaxone","Injection","1000 mg","TRIAWA-1000","Sands Active, Sri Lanka","Sands Active, Sri Lanka",1025.38,"Vial"],
  [255,"Ciprofloxacin","Tablet","500 mg","ULTRAFLOX-500","Bal Pharma, India","Yaden International",16.88,"Tablet"],
  [256,"Flucloxacillin","Injection","500 mg","UNIFLOX 500","Navesta, Sri Lanka","Navesta, Sri Lanka",907.95,"Vial"],
  [257,"Progesterone","Vaginal gel","8%","VAGESTON","Zydus Healthcare, India","Hemas Pharmaceuticals",883.00,"1.35g Tube"],
  [258,"Clotrimazole","Pessary","100 mg","VAGID","Bliss GVS, India","Sunshine Healthcare",69.48,"Pessary"],
  [259,"Vancomycin","Injection","1000 mg","VANCOTECH 1000","United Biotech, India","Klintas (Pvt) Ltd.",2628.38,"Vial"],
  [260,"Varicella vaccine","Injection","2000 PFU","VARILRIX","Glaxo, Belgium","Baur & Co.",8910.00,"Vial"],
  [261,"Vasopressin","Injection","20 IU/mL","Vasopressin","Kelun Lifescience, Sri Lanka","Kelun Lifescience, Sri Lanka",4058.67,"1 mL"],
  [262,"Trimetazidine","Tablet (modified release)","35 mg","VASTAREL MR","Les Laboratories, France","Hemas Pharmaceuticals",49.31,"Tablet"],
  [263,"Clobazam","Tablet","5 mg","VERCLOB","Verve Human Care, India","Leader Pharma",32.00,"Tablet"],
  [264,"Betahistine","Tablet","24 mg","VERTIWA 24","Sands Active, Sri Lanka","Sands Active, Sri Lanka",48.00,"Tablet"],
  [265,"Betahistine","Tablet","8 mg","VERTIWA 8","Sands Active, Sri Lanka","Sands Active, Sri Lanka",18.75,"Tablet"],
  [266,"Vildagliptin","Tablet","50 mg","VILDIPP 50","Sun Pharmaceutical, India","Emerchemie NB",68.18,"Tablet"],
  [267,"Erythropoietin","Injection","4000 IU/mL","VINTOR 4000","Genova, India","Emerchemie NB",1736.95,"Pre-filled syringe"],
  [268,"Mebendazole","Tablet","500 mg","Wormin 500","Cadila Pharmaceuticals, India","Sunshine Healthcare",50.25,"Tablet"],
  [269,"Insulin Biphasic Isophane","Injection","100 IU/mL","WOSULIN-30/70","Wockhardt, India","Emerchemie NB",913.14,"3mL Cartridge"],
  [270,"Insulin Biphasic Isophane","Injection","100 IU/mL","WOSULIN-30/70","Wockhardt, India","Emerchemie NB",1811.39,"3mL Vial"],
  [271,"Bisoprolol","Tablet","5 mg","Zabesta 5","USV Pvt Ltd, India","Hemas Pharmaceuticals",35.00,"Tablet"],
  [272,"Calcium + Cholecalciferol","Tablet (chewable)","1250 mg + 400 IU","ZECARB D+","Celogen, Sri Lanka","Celogen, Sri Lanka",30.00,"Tablet"],
  [273,"Compound benzoic acid","Ointment","-","ZEN WHITFIELD'S","Nanz Med Science, India","SMM Halcyon",296.58,"15g"],
  [274,"Zoledronic acid","Injection","4mg","ZOLDRON","Getwell Pharma, India","Esses Pharmacy",8174.39,"Vial"],
  [275,"Bisacodyl","Suppository","10mg","ZYCOLAX-10","Zydus Life Science, India","Hemas Pharmaceuticals",64.33,"Suppository"],
  [276,"Abacavir","Tablet","300mg","Abacavir","Celogen, Sri Lanka","Celogen, Sri Lanka",350.00,"Tablet"],
  [277,"Abiraterone acetate","Tablet","250mg","Abirone","Hetero Labs, India","Mansel Ceylon",464.01,"Tablet"],
  [278,"Aciclovir Sodium","Infusion","250mg","Aciclovir Sodium","Ciron Drugs, India","Ceyoka (Pvt) Ltd.",978.00,"Vial"],
  [279,"Alcohol Based Hand Rub","Solution","-","Setallium","Suraksha Pharma, Sri Lanka","Suraksha Pharma, Sri Lanka",405.00,"500mL"],
  [280,"Alfacalcidol","Capsule","0.25mcg","Aldiol","Softgel Healthcare, India","Pharma Associates",10.00,"Capsule"],
  [281,"Amisulpride","Tablet","100mg","AMIDE 100","Celogen Lanka, Sri Lanka","Celogen Lanka, Sri Lanka",26.50,"Tablet"],
  [282,"Amlodipine","Tablet","5 mg","Angicam 5","Blue Cross Laboratories, India","Sunshine Healthcare Lanka",9.77,"Tablet"],
  [283,"Amoxicillin + Clavulanate","Oral Suspension","156.25mg/5mL","Indclav 156","Indchemie Health, India","Pharma Associates",571.06,"100mL"],
  [284,"Amoxicillin + Clavulanate","Tablet","1000mg","Indclav 1000","Indchemie Health, India","Pharma Associates",70.00,"Tablet"],
  [285,"Apixaban","Tablet","2.5 mg","APIX 2.5","The ACME Laboratories, Bangladesh","Mega Pharma",77.49,"Tablet"],
  [286,"Apixaban","Tablet","2.5 mg","ACTICA-2.5","Micro Labs, India","Micro Healthcare",81.50,"Tablet"],
  [287,"Apixaban","Tablet","5 mg","ACTICA-5","Micro Labs, India","Micro Healthcare",120.00,"Tablet"],
  [288,"Ascorbic acid","Chewable Tablet","500 mg","C-GEN 500","Newgen Lanka, Sri Lanka","Newgen Lanka, Sri Lanka",22.50,"Tablet"],
  [289,"Atenolol","Tablet","50 mg","Ateleb-50","Leben Laboratories, India","Ceyoka (Pvt) Ltd.",2.40,"Tablet"],
  [290,"Atomoxetine","Capsule","18mg","Attentrol 18","Sun Pharmaceuticals, India","Emerchemie NB",99.88,"Capsule"],
  [291,"Atorvastatin","Tablet","40 mg","LIPITOR","Viatris, Germany","Hemas Pharmaceuticals",49.17,"Tablet"],
  [292,"Azithromycin","Tablet","500 mg","Zydzith-500","Cadila Healthcare, India","Sunshine Healthcare Lanka",97.65,"Tablet"],
  [293,"Beclometasone","Aqueous Nasal Spray","50 mcg","BECLOMATE NS 50","Jewim Pharmaceutical, China","Emerchemie NB",694.17,"200 Sprays Bottle"],
  [294,"Betahistine","Tablet","16 mg","BE-Steady 16","Aurobindo Pharma, India","Alaris Lanka",14.17,"Tablet"],
  [295,"Betahistine","Tablet","8 mg","BE-Steady 8","Aurobindo Pharma, India","Alaris Lanka",9.13,"Tablet"],
  [296,"Betamethasone + Salicylic Acid","Ointment","-","Beprosalic","HOE Pharmaceuticals, Malaysia","Indoscan (Pvt) Ltd.",777.12,"15g tube"],
  [297,"Bevacizumab","Infusion","100mg/4 mL","Versavo 100","Dr. Reddy's Laboratories","Emerchemie NB",30588.04,"Vial"],
  [298,"Bevacizumab","Infusion","400mg/16mL","Versavo 400","Dr. Reddy's Laboratories","Emerchemie NB",89579.26,"Vial"],
  [299,"Bisacodyl","Tablet (delayed release)","5mg","CORLEX","Akums Drugs, India","Sterix Healthcare",4.95,"Tablet"],
  [300,"Bisoprolol","Tablet","5mg","Bisogen 5","Newgen Lanka, Sri Lanka","Newgen Lanka, Sri Lanka",19.25,"Tablet"],
  [301,"Poliomyelitis vaccine","Vaccine","Type 1 & 3","BIOPOLIO B1/3","Bharat Biotech, India","Gulf Pharma",1863.10,"20 doses"],
  [302,"Poliomyelitis vaccine","Vaccine","Type 1 & 3","BIOPOLIO B1/3","Bharat Biotech, India","Gulf Pharma",931.55,"10 doses"],
  [303,"Brimonidine + Timolol","Eye Drops","-","COMBIGAN","Allergan Pharmaceuticals, Ireland","Hemas Pharmaceuticals",3003.35,"5mL"],
  [304,"Brimonidine Tartrate","Eye Drops","0.1%","Brimonidine Tartrate","Allergan Sales, USA","Hemas Pharmaceuticals",2492.00,"5mL"],
  [305,"Cabergoline","Tablet","0.5mg","Cabergoline","Treffer Pharmaceuticals, India","Yaden International",277.99,"Tablet"],
  [306,"Calcipotriol","Ointment","0.005%","Caligen","Newgen Lanka, Sri Lanka","Newgen Lanka, Sri Lanka",3000.00,"15g"],
  [307,"Calcipotriol","Ointment","0.005%","Caligen","Newgen Lanka, Sri Lanka","Newgen Lanka, Sri Lanka",4000.00,"30g"],
  [308,"Calcium + Vitamin D3","Soft Gelatin Capsule","250mg + 400IU","MOMCAL","Contract Manufacturing, Australia","Alaris Lanka",35.12,"Capsule"],
  [309,"Calcium Carbonate + Vitamin D3","Soft Gelatin Capsule","625mg + 400IU","THERACAL","Contract Manufacturing, Australia","Alaris Lanka",44.78,"Capsule"],
  [310,"Calcium Folinate","Injection","50mg","FOLINEX 50","Beacon Pharmaceuticals, Bangladesh","Emerchemie NB",1822.00,"Vial"],
  [311,"Candesartan","Tablet","16 mg","Treatan 16","CIC Holding, Sri Lanka","CIC Holding, Sri Lanka",65.00,"Tablet"],
  [312,"Carbimazole","Tablet","10mg","CARBIZ-10","Celogen Lanka, Sri Lanka","Celogen Lanka, Sri Lanka",28.50,"Tablet"],
  [313,"Carvedilol","Tablet","6.25mg","CONDIL-6.25","Celogen Lanka, Sri Lanka","Celogen Lanka, Sri Lanka",10.30,"Tablet"],
  [314,"Carvedilol","Tablet","12.5mg","CONDIL 12.5","Celogen Lanka, Sri Lanka","Celogen Lanka, Sri Lanka",19.80,"Tablet"],
  [315,"Carvedilol","Tablet","3.125mg","Betadol 3.125","Centurion Laboratories, India","Yaden International",8.00,"Tablet"],
  [316,"Cefepime","Injection","1000mg","MELPIM 1000","Sands Active, Sri Lanka","Sands Active, Sri Lanka",1094.40,"Vial"],
  [317,"Cefepime","Injection","500mg","Dizma 4","Zafa Pharmaceutical, India","Yaden International",629.64,"Vial"],
  [318,"Ceftazidime","Injection","1000mg","C-TZID 1000","Sands Active, Sri Lanka","Sands Active, Sri Lanka",880.00,"Vial"],
  [319,"Ceftriaxone","Injection","500mg","TRIAXIWA 500","Sands Active, Sri Lanka","Sands Active, Sri Lanka",690.00,"Vial"],
  [320,"Cefuroxime Axetil","Tablet","125mg","MILCEF 125","The Madras Pharmaceuticals, India","Pharma Associates",51.73,"Tablet"],
  [321,"Cefuroxime Axetil","Tablet","250mg","RITIL-250","Micro Labs, India","Micro Healthcare",66.87,"Tablet"],
  [322,"Celecoxib","Capsule","100mg","Celecoxib","Zydus Lifesciences, India","Sunshine Healthcare Lanka",7.21,"Capsule"],
  [323,"Cephalexin","Capsule","500mg","Nexporin-500","Scott-Edil, India","Slim Pharmaceuticals",29.71,"Capsule"],
  [324,"Cephalexin","Oral Suspension","125mg/5 mL","Cephadex","Medispray, India","Breathe Free Lanka",296.00,"100 mL"],
  [325,"Ascorbic Acid","Chewable Tablet","500mg","ASBIC-O","Celogen Lanka, Sri Lanka","Celogen Lanka, Sri Lanka",20.00,"Tablet"],
  [326,"Chlorpheniramine Maleate","Oral Solution","2 mg/5mL","Hymine","ACE Healthcare, Sri Lanka","ACE Healthcare, Sri Lanka",150.00,"60mL"],
  [327,"Chlorpheniramine Maleate","Oral Solution","2 mg/5mL","Hymine","ACE Healthcare, Sri Lanka","ACE Healthcare, Sri Lanka",208.00,"100mL"],
  [328,"Chlorpheniramine Maleate","Oral Solution","2 mg/5mL","Hymine","ACE Healthcare, Sri Lanka","ACE Healthcare, Sri Lanka",650.00,"500mL"],
  [329,"Chlorpheniramine Maleate","Tablet","4mg","ALLERMINE","Astron, Sri Lanka","Astron, Sri Lanka",2.00,"Tablet"],
  [330,"Cholecalciferol","Tablet","1000IU","Prove D3-1000IU","PT Dankos Pharma, Indonesia","Hemas Pharmaceuticals",13.23,"Tablet"],
  [331,"Ciprofloxacin","Eye/Ear Drop","0.30%","CIPROCIN","Square Pharmaceuticals, Bangladesh","CIC Holdings",202.95,"5mL"],
  [332,"Cisatracurium Besylate","Injection","10mg/5mL","CISATRA","Themis Medicare, India","Sunshine Healthcare Lanka",2610.38,"Vial"],
  [333,"Clarithromycin","Tablet","500mg","Clarigen 500","Newgen Lanka, Sri Lanka","Newgen Lanka, Sri Lanka",90.00,"Tablet"],
  [334,"Clindamycin","Capsule","300mg","LINDAMAX 300","Eskayef Pharmaceuticals, Bangladesh","Truvic (Pvt) Ltd.",73.00,"Capsule"],
  [335,"Clonazepam","Tablet","2mg","Clonazepam","Mercury Laboratories, India","Yaden International",28.00,"Tablet"],
  [336,"Clonazepam","Tablet","0.5mg","Clonazepam","Morison, Sri Lanka","Morison, Sri Lanka",5.10,"Tablet"],
  [337,"Clotrimazole","Vaginal Tablet","100mg","Mycoril","Remedica, Cyprus","Kandana Foods and Drugs",175.87,"Tablet"],
  [338,"Co-amoxiclav","Injection","1.2g","CLANEKSI","PT Sanbe, Indonesia","Softlogic Pharmaceuticals",1025.54,"Vial"],
  [339,"Compound Sodium Lactate","Infusion","-","Compound Sodium Lactate","Aculife Healthcare, India","Emerchemie NB",205.56,"500mL"],
  [340,"Compound Sodium Lactate","Infusion","-","Compound Sodium Lactate","Aculife Healthcare, India","Emerchemie NB",300.82,"1000mL"],
  [341,"Cyclosporine","Capsule","25mg","Cyclosporine","Centurion Laboratories, India","Yaden International",290.00,"Capsule"],
  [342,"Dapagliflozin","Tablet","10mg","Dapaget 10","Getz Pharma, Pakistan","Hemas Pharmaceuticals",109.93,"Tablet"],
  [343,"Dapagliflozin","Tablet","10mg","DIABFLOZ 10","Finecure Pharmaceuticals, India","Biolife Pharmaceuticals",104.00,"Tablet"],
  [344,"Dapagliflozin","Tablet","5mg","Dapaget 5","Getz Pharma, Pakistan","Hemas Pharmaceuticals",88.04,"Tablet"],
  [345,"Dapagliflozin","Tablet","5mg","INVAFLOZIN 5","Inventia Healthcare, India","Emerchemie NB",38.13,"Tablet"],
  [346,"Darbepoetin Alfa","Injection","60mcg/0.30mL","DERISE 60","Hetero Biopharma, India","Divasa Pharma",17554.86,"Pre-filled syringe"],
  [347,"Dexamethasone","Injection","8mg/2mL","Dexamethasone","Kelun Lifescience, Sri Lanka","Kelun Lifesciences, Sri Lanka",45.00,"Ampoule"],
  [348,"Dienogest","Tablet","2mg","Visanne","Bayer Weimar GmbH, Germany","Hemas Pharmaceuticals",487.11,"Tablet"],
  [349,"Digoxin","Injection","250mcg/mL","DIGIVER","Verve Human Care, India","Leader Pharma",354.00,"2mL"],
  [350,"Dipyridamole","Tablet","100mg","Pyrigen 100","Newgen Lanka, Sri Lanka","Newgen Lanka, Sri Lanka",22.20,"Tablet"]
];

// Build the JSON database grouped by generic name
const database = {
  metadata: {
    source: "National Medicines Regulatory Authority (NMRA), Sri Lanka",
    description: "Maximum Retail Prices for pharmaceuticals in Sri Lanka",
    currency: "LKR",
    currencySymbol: "Rs.",
    totalEntries: rawEntries.length,
    lastUpdated: "2026-03-05",
    disclaimer: "Prices are Maximum Retail Prices (MRP) per unit as gazetted by NMRA Sri Lanka"
  },
  drugs: {}
};

for (const entry of rawEntries) {
  const [no, genericName, dosageForm, strength, brandName, manufacturer, marketAuthHolder, price, priceUnit] = entry;
  
  // Normalize generic name as key
  const key = genericName.toLowerCase().trim();
  
  if (!database.drugs[key]) {
    database.drugs[key] = [];
  }
  
  database.drugs[key].push({
    id: no,
    brandName,
    genericName,
    dosageForm,
    strength,
    manufacturer,
    marketAuthHolder,
    price,
    priceUnit,
    currency: "LKR"
  });
}

// Sort each generic's brands by price
for (const key of Object.keys(database.drugs)) {
  database.drugs[key].sort((a, b) => a.price - b.price);
}

// Write the output
const fs = require('fs');
const outputPath = require('path').join(__dirname, 'sri_lankan_drug_prices.json');
fs.writeFileSync(outputPath, JSON.stringify(database, null, 2), 'utf8');

console.log(`✅ Generated ${outputPath}`);
console.log(`   Total entries: ${rawEntries.length}`);
console.log(`   Unique generics: ${Object.keys(database.drugs).length}`);
console.log(`   Sample generics with multiple brands:`);

// Show generics with multiple brands (most useful for comparison)
const multiBrand = Object.entries(database.drugs)
  .filter(([k, v]) => v.length >= 2)
  .sort((a, b) => b[1].length - a[1].length);

for (const [name, brands] of multiBrand.slice(0, 15)) {
  console.log(`   - ${name}: ${brands.length} brands (Rs. ${brands[0].price} - Rs. ${brands[brands.length-1].price})`);
}
